In [1]:
import numpy as np

In [2]:
x = np.arange(10).reshape(2,5)
np.vsplit(x,2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [3]:
a = np.arange(10).reshape(2,5)
b = np.ones(10).reshape(2,5)

np.vstack((a,b))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
a = np.arange(10).reshape(2,5)
b = np.ones(10).reshape(2,5)

np.hstack((a,b))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

# Question:4
How to convert an array of arrays into a flat 1d array.

In [8]:
x = np.array([[0,1,2,3,4],[5,6,7,8,9]])
x.reshape(10,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question:5
How to Convert higher dimension into one dimension?

In [16]:
a = np.arange(15)
np.hsplit(a,5)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14])]

# Question:7
Create 5x5 an array and find the square of an array?

In [20]:
c = np.arange(25).reshape(5,5)
np.sqrt(c)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

# Question:8
Create 5x6 an array and find the mean?

In [24]:
x = np.arange(30).reshape(5,6)
np.mean(x)

14.5

# Question:9
Find the standard deviation of the previous array in Q8?

In [26]:
np.std(x)

8.65544144839919

# Question:10
Find the median of the previous array in Q8?

In [28]:
np.median(x)

14.5

# Question:11
Find the transpose of the previous array in Q8?

In [30]:
np.transpose(x)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# Question:12
Create a 4x4 an array and find the sum of diagonal elements?

In [36]:
z = np.arange(16).reshape(4,4)
np.trace(z)

30

# Question:13
Find the determinant of the previous array in Q12?

In [38]:
np.linalg.det(z)

-2.9582283945787796e-30

# Question:14
Find the 5th and 95th percentile of an array?

In [43]:
v = np.arange(20)
t = np.percentile(v,5)
u = np.percentile(v,95)

print(t)
print(u)

0.9500000000000001
18.05


# Question:15
How to find if a given array has any null values?

In [45]:
r = np.random.randn(20)
np.isnan(r)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])